/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

config { hasOutput: true, tags: ["theta", "udfs"] }

CREATE OR REPLACE FUNCTION ${self()}(sketchA BYTES, sketchB BYTES, seed INT64)
RETURNS BYTES
OPTIONS (
  description = '''Computes a sketch that represents the intersection of two given sketches.

Param sketchA: the first sketch as BYTES.
Param sketchB: the second sketch as BYTES.
Param seed: This is used to confirm that the given sketches were configured with the correct seed.
Returns: a Compact, Compressed Theta Sketch, as BYTES.

This is the .mjs-compatible version that uses aggregation internally.

For more information:
 - https://datasketches.apache.org/docs/Theta/ThetaSketches.html
'''
) AS ((
  SELECT ${ref("theta_sketch_intersection_agg")}(sketch, seed)
  FROM UNNEST([sketchA, sketchB]) AS sketch
  WHERE sketch IS NOT NULL
));